### model
model_name_or_path: Predenergy
trust_remote_code: true


### method
finetuning_type: full
deepspeed: ./data/Predenergy/Pretrain/config/pretrain.json


### dataset
dataset: ETSD_Large_Scale
template: deepseek3
cutoff_len: 40000
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16


###output
output_dir: ./data/Predenergy/Pretrain/outputs
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true


### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 18000000