# STDM Parameters
enc_in: 1
dec_in: 1
c_out: 1
e_layers: 2
d_layers: 1
d_model: 512
d_ff: 2048
hidden_size: 256
freq: 'h'
factor: 1
n_heads: 8
seg_len: 6
win_size: 2
activation: 'gelu'
output_attention: 0
patch_len: 16
stride: 8
period_len: 4
dropout: 0.2
fc_dropout: 0.2
moving_avg: 25
batch_size: 256
lradj: 'type3'
lr: 0.02
num_epochs: 100
num_workers: 0
loss: 'huber'
patience: 10
num_experts: 4
noisy_gating: true
k: 1
CI: true
seq_len: 96
horizon: 24
pred_len: 24

# MoTSE Parameters
motse_hidden_size: 512
motse_intermediate_size: 1024
motse_num_hidden_layers: 4
motse_num_attention_heads: 8
motse_num_key_value_heads: 8
motse_hidden_act: 'silu'
motse_num_experts_per_tok: 2
motse_num_experts: 4
motse_max_position_embeddings: 2048
motse_initializer_range: 0.02
motse_rms_norm_eps: 1e-6
motse_use_cache: true
motse_use_dense: false
motse_rope_theta: 10000
motse_attention_dropout: 0.0
motse_apply_aux_loss: true
motse_router_aux_loss_factor: 0.02
motse_tie_word_embeddings: false
motse_input_size: 1
motse_horizon_lengths: [24]
motse_attn_implementation: 'eager'

# Connection Parameters
connection_type: 'adaptive'  # 'linear', 'attention', 'concat', 'adaptive'
connection_dropout: 0.1
connection_hidden_size: 256

# Advanced Connection Parameters
use_cross_attention: true
use_residual_connection: true
use_layer_norm: true

# Model Selection
use_combined_model: true

# Data Processing Parameters
data_loader_type: 'standard'  # 'standard', 'universal', 'forecasting'
features: 'S'  # 'S' for univariate, 'M' for multivariate
target: 'OT'
timeenc: 0
normalize: 2  # 0: no normalization, 1: standard scaler, 2: min-max scaler
train_ratio: 0.7
val_ratio: 0.2
shuffle: true
max_pack_length: null  # null for auto calculation

# Training Parameters
optimizer: 'adam'
scheduler: 'cosine'
warmup_steps: 1000
gradient_clip_val: 1.0
accumulate_grad_batches: 1
precision: '32'  # '16', '32', 'bf16'

# Evaluation Parameters
eval_batch_size: 64
eval_strategy: 'epoch'
save_strategy: 'epoch'
load_best_model_at_end: true
metric_for_best_model: 'val_loss'
greater_is_better: false

# Logging Parameters
logging_steps: 100
save_steps: 1000
eval_steps: 1000
report_to: 'tensorboard'
logging_dir: './logs'
logging_first_step: true
logging_strategy: 'steps' 