# Predenergy Standard Configuration
# This configuration uses the standard STDM-only architecture

# === Core Prediction Parameters ===
seq_len: 96                    # Input sequence length
horizon: 24                    # Prediction horizon
label_len: 48                  # Label length for decoder
input_size: 1                  # Input feature dimension
c_out: 1                       # Output dimension

# === Model Architecture ===
d_model: 512                   # Model dimension
n_heads: 8                     # Number of attention heads
e_layers: 2                    # Number of encoder layers
d_layers: 1                    # Number of decoder layers
d_ff: 2048                     # Feedforward dimension
dropout: 0.1                   # Dropout rate
activation: "gelu"             # Activation function

# === Attention Parameters ===
factor: 5                      # Attention factor
output_attention: false        # Output attention weights

# === Training Parameters ===
batch_size: 32                 # Batch size
learning_rate: 0.001           # Learning rate
num_epochs: 100                # Number of epochs
patience: 10                   # Early stopping patience
loss_function: "huber"         # Loss function type

# === Data Processing ===
features: "S"                  # S for univariate, M for multivariate
target: "OT"                   # Target column name
normalize: 2                   # Normalization method
freq: "h"                      # Frequency string
embed: "timeF"                 # Embedding type

# === Advanced Model Options ===
use_combined_model: false      # Use STDM+MoTSE combined architecture
use_layer_norm: true           # Use layer normalization
use_revin: true                # Use RevIN normalization
moving_avg: 25                 # Moving average window

# === STDM Specific Parameters ===
CI: true                       # Channel independence
distil: true                   # Use distillation

# === Device and Performance ===
device: "auto"                 # Device selection (auto/cuda/cpu)
mixed_precision: true          # Use mixed precision training